### PR TITLE
Heroku-CLI change: don't pass `--confirm` to `pg:push`

### LINKED ISSUE #128: Unexpected flag `--confirm` when restoring to remote environment
Hi there!

When running the `staging restore development` command from my Linux machine, I receive the following error:

screen shot 2017-05-02 at 1 36 28 pm

I just installed the latest version of Parity using the "On Debian" instructions. 

Here is the result of `heroku --version`:

```
heroku-toolbelt/3.43.16 (x86_64-linux) ruby/2.3.3
heroku-cli/5.9.0-1b8deac (linux-amd64) go1.7.5
```

The error message seems to be indicating that the `--confirm` flag is no longer supported, but I can't find any information about that in the Heroku documentation or otherwise. Not sure if maybe I have an old version of the toolbelt installed. 

Has anyone else run into this?

### PR DESCRIPTION
**Pull request by geoffharcourt**
Heroku's `pg:push` CLI no longer accepts the `--confirm` argument, as it
expects the remote database to already be reset before overwriting it
with a backup.

Before restoring to a remote environment, we reset the remote database
with `pg:reset`. We will pass a confirm argument to `pg:reset`. To
accomplish this, the mechanism to determine the remote application name
(not the git remote) has been extracted into its own object.

Fix #128.

### CODE REVIEW

File: spec/parity/backup_spec.rb [hunk 1]
```diff
@@ -23,27 +23,36 @@
...
   it "restores backups to staging from development" do
+    stub_heroku_app_name
     allow(IO).to receive(:read).and_return(database_fixture)
     allow(Kernel).to receive(:system)
 
     Parity::Backup.new(from: "development", to: "staging").restore
 
     expect(Kernel).
       to have_received(:system).
+      with(heroku_staging_pg_reset)
```
Comment (mwenger1) [inline spec/parity/backup_spec.rb]: I believe this test requires that `parity-staging` is the same in both `stub_heroku_app_name` and `heroku_staging_pg_reset`. That wasn't clear to me in reading the spec initially.

Consider updating both methods to taking name as an optional argument so that this can become:

```
app_name = "parity-staging"
stub_heroku_app_name(app_name)

.with(heroku_staging_pg_reset(app_name))
```
