### PR TITLE
Fix `deploy` problems in 0.9.0

### LINKED ISSUE #61: `deploy` in 0.9.0 sometimes fails if migrations need to be run
From @bernerdschaefer:

Environment bins expect all commands to return an exit status, but `deploy` does not always return an exit status, depending on the current state of migrations on the remote server.

### PR DESCRIPTION
**Pull request by geoffharcourt**
v0.9.0 broke `deploy` in two ways. The first is that migrations were
being checked after the deploy completed, which resulted in the check
for diffs in `db/migrate` always finding no differences. This change
reverts to the prior pattern of caching whether migrations are pending
at the start of `deploy` before pushing to Heroku.

The second is that the check for `rake` would raise an exception if a
user's local bundle wasn't installed, as the shell command would return
a failing status. `Kernel.system` can return `true`, `false`, or `nil`,
but `Kernel.exit` can't accept `nil` as an argument.
`Parity::Environment#run` will now always return a boolean value so that
`Kernel.exit` receives an appropriate argument.

Fix #61.

### CODE REVIEW

File: lib/parity/environment.rb [hunk 1]
```diff
@@ -37,7 +41,9 @@ def backup
     end
 
     def deploy
-      if deploy_to_heroku && run_migration?
+      pending_migrations = run_migration?
+
+      if deploy_to_heroku && pending_migrations
         migrate
       end
```
Comment (bernerdschaefer) [inline lib/parity/environment.rb]: I *think* the problem here is that if there are no pending migrations, this will return `nil`, because that's what `if` returns.

I think the behavior we want for this is:

```ruby
def deploy
  deploy_to_heroku && migrate_if_needed
end

def migrate_if_needed
  if run_migration?
    migrate
  else
    true
  end
end
```

Comment (bernerdschaefer) [inline lib/parity/environment.rb]: Oh, I missed the ` || false` up at the top.

Comment (bernerdschaefer) [inline lib/parity/environment.rb]: Actually, I think the default `|| false` will cause this method to exit with a non-zero status code if there's no migration to run.

Comment (geoffharcourt) [inline lib/parity/environment.rb]: @bernerdschaefer that makes sense. The annoying part is that we have to check for whether we need to migration _before_ we deploy, or else the diff finds nothing to change (this was my mistake on the last version, changing this order). It results in a clunky sequence where we are checking whether we need to migrate, saving that result, then deploying, _then_ running the migrations if needed.

**Comment by geoffharcourt** [comment]
@bernerdschaefer added specs to test that `Parity::Environment#run` with `deploy` subcommand:

1. failed deployment always returns false
2. successful deploy with no necessary migrations returns true

File: lib/parity/environment.rb [hunk 2]
```diff
@@ -128,7 +138,7 @@ def basename
     end
 
     def run_migration?
-      rails_app? && pending_migrations?
+      pending_migrations? && rails_app?
```
Comment (bernerdschaefer) [inline lib/parity/environment.rb]: Is swapping the order significant to this PR?

Comment (geoffharcourt) [inline lib/parity/environment.rb]: No. The `rails_app?` step takes longer, so I was putting it off until it was necessary, but we should constrain the scope here, I'll undo this change.

File: lib/parity/environment.rb [hunk 3]
```diff
@@ -37,8 +41,14 @@ def backup
     end
 
     def deploy
-      if deploy_to_heroku && run_migration?
+      pending_migrations = run_migration?
+
+      deployed = deploy_to_heroku
```
Comment (bernerdschaefer) [inline lib/parity/environment.rb]: The required ordering and caching of values in this method makes it surprisingly complex. I don't have any particularly great ideas for cleaning it up, but what about:

```ruby
skip_migrate = !run_migration?

if deploy_to_heroku
  skip_migrate || migrate
end
```

Comment (geoffharcourt) [inline lib/parity/environment.rb]: Yeah, I'm really not wild about this code as it stands. As another alternative, we could save state. Your suggestion is an improvement over what's there, I'll implement it.

Comment (geoffharcourt) [inline lib/parity/environment.rb]: Ack, this doesn't work because if `deploy_to_heroku` fails, we want to return an exit status of `1`.

**Comment by geoffharcourt** [comment]
@bernerdschaefer the resulting code looks better now. I'm a little worried that the intent is harder to discern from the way it's organized, but we do have specs checking that things happen in the correct order, so I think your suggestion is an improvement.

**Comment by bernerdschaefer** [comment]
Awesome. This looks great, and I'm happy to see us getting exit codes right with parity!

:+1:
