### PR TITLE
Parse database.yml that uses ERB

### LINKED ISSUE #73: Parse ERB in `database.yml`
Rails allows a user to use ERB within a YAML file to set up dynamic values for keys. On apps that employ this approach, Parity will fail when attempting to parse `config/database.yml`.

### PR DESCRIPTION
**Pull request by geoffharcourt**
Rails allows the use of ERB to define dynamic values in `database.yml`.
If the database name in development is defined using a dynamic value,
the ERB syntax is passed in as an argument to Heroku-CLI rather than the
desired name.

This change parses `database.yml` as an ERB template, reading in any
development variables from the `.env` file as needed.

Other changes:
- development-only gems are sectioned off into a separate group in the
  Gemfile

Close #73.

### CODE REVIEW

File: spec/parity/backup_spec.rb [hunk 1]
```diff
@@ -15,6 +17,27 @@
       with(heroku_production_to_development_passthrough)
   end
 
+  it "correctly parses database.yml files that include ERB and environment variables" do
+    database_name = "parity_erb_development"
+    ClimateControl.modify DEVELOPMENT_DATABASE_NAME: database_name do
```
Comment (seanpdoyle) [inline spec/parity/backup_spec.rb]: what do you think about invoking this in an `around` block so that the tests aren't so deeply nested?

Comment (geoffharcourt) [inline spec/parity/backup_spec.rb]: I think if I do that I have to specify the DB name inside and outside the block. I'm open to that change, but since it's only relevant in one example I'm not sure if setting up a separate context is worth it.

**Comment by bernerdschaefer** [comment]
@geoffharcourt I'm curious about what ERB snippets you've been seeing included in the development database configuration. I don't think I've personally come across apps which use ENV variables to change the development database name, which seems to be the only attribute we're using.

I just want to push back on this a little bit, since this looks like it would be the first parity feature that ties us to a Ruby implementation of parity. At the moment, it could be distributed as a pile of bash scripts without breaking any features for the users of parity. Having some flexibility in implementation language could be helpful in continuing to iterate on the best way to distribute and run parity across many environments.

Otherwise :+1:

**Comment by bernerdschaefer** [comment]
Could the cases where the `database.yml` does depend on its environment and ERB be handled with a flag to specify the local database name? For example, `development restore-from production --into other_db_name` could actually be a useful feature on its own.

**Comment by geoffharcourt** [comment]
@bernerdschaefer we currently depend on `database.yml` being present, and since we bundle with Travelling Ruby, there's no need for the Python or Go developer to need their own installed Ruby gems, even after this change.

**Comment by bernerdschaefer** [comment]
@geoffharcourt Understood on that front.

I more wanted to start a discussion about the cost / benefit of this feature, as far as the implementation of parity itself.

A pretty clear upside is that it supports more cases out of the box.

A downside is that parity must be able to execute arbitrary Ruby code to operate correctly. This is not currently the case.

I'd be curious to hear how common it is for people to have problems with ERB values for development database names, and whether, for example, a command-line flag, could also address the issue.

**Comment by geoffharcourt** [comment]
@bernerdschaefer I hear you. This PR came about because my current client's application is unusable with Parity due to ERB in their template. I'm not sure how many other teams have this problem, but I have seen this pattern in apps before.

File: spec/parity/backup_spec.rb (hunk 1 above)
Comment (geoffharcourt) [inline spec/parity/backup_spec.rb]: @seanpdoyle I think this is an improvement with your recommendation.

**Comment by geoffharcourt** [comment]
@bernerdschaefer and @seanpdoyle thanks as usual for the detailed :eyeglasses:.
